### ISSUE TITLE
Unexpected result of the linear regression

### ISSUE THREAD

**Issue by vreyespue** [titoeb/rf_vs_trend#1]
Sorry for asking this (maybe very trivial) question, but why is the result of the following code not simply a line? How many dimensions does `X_train` and `X_test` contain? And if only one dimension, then why don't you get just a straight line as result?
```
# Fit the linear regression to the data
linear_regression = LinearRegression()
linear_regression.fit(X_train, y_train.values.reshape(-1))

# Create predictions
y_pred_linear_regression = y_test.copy()
y_pred_linear_regression.loc[:, "data"] = linear_regression.predict(X_test.values)
```
Many thanks 😄  and great work, I did not think about the lack of trend fitting by the random forest. Interesting!
PS: There are some typos in the axis labels, e.g. "Precictions" 👍

**Comment by titoeb** [comment]
Hi Vicente!
Thank you for taking the time to look at my notebook. In the latest commit I tried to catch all the typos, but as know that's not exactly my strong point.

Considering the straight line of the regression I know where you getting from. If the regression would get the position of the time series as input (0, ..., n_time_points) then indeed it should predict a straight line. That's a great catch! But that's not what I am doing in this notebook. Here I  always predict the next value in the time series with the a past value of the time-series. You can see this in the 'create_train_from_ts' function, where I create the  data the models are trained on. Specifying 'lag' accordingly, the models get the n_lagged value as input to predict the current value. Therefore, what the linear model currently does it that it predicts just the value one day before as its parameter is 1 (therefore in the plot, the predictions show exactly the true data, but slightly lagged).

There are some issue with what I doing here in the sense of a real data science project. Using a lag of 1 and prediction quite a few data points in the future, I effectively use future data (from the point of validation begin). Therefore, you need to interpret this not as a single train / test split but many back tests  that I am running subsequently.

I hope that helps you to understand and that the issue is resolved for you.

P.S. I think this tutorial might help you in understand what I mean even better:
https://machinelearningmastery.com/backtest-machine-learning-models-time-series-forecasting/

**Comment by vreyespue** [comment]
Hi @titoeb 😃 
thank you very much for your great explanation and for the reference link!
So in my own words, I understand that you do a scatter plot of the value on the day before vs. after (because `lag=1`), thereby computing a linear regression out of it. Afterwards, you plot the real vs. predicted values along the time axis (i.e. from Jan to Dec 2019).
I think two improvements might be done:

1. Add the scatter plot and the resulting linear regression into the notebook, so that the reader can easily understand the flow of analysis, and
2. Make clear that your test data is the newest one (in this case starting on Aug 2019). Normally one would expect the test and training data to be intermingled in time (but this is just my humble opinion 😃 ).

Anyhow, very interesting analysis! 😄  great work! 👍
